#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 96
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 14

enum {
  sym_comment = 1,
  sym_string = 2,
  sym_number = 3,
  sym_identifier = 4,
  sym__line_terminator = 5,
  anon_sym_LPAREN = 6,
  anon_sym_COMMA = 7,
  anon_sym_RPAREN = 8,
  anon_sym_COLON = 9,
  anon_sym_DOT = 10,
  anon_sym_LBRACE = 11,
  anon_sym_RBRACE = 12,
  anon_sym_LBRACK = 13,
  anon_sym_RBRACK = 14,
  anon_sym_EQ_EQ = 15,
  anon_sym_BANG_EQ = 16,
  anon_sym_LT = 17,
  anon_sym_GT = 18,
  anon_sym_LT_EQ = 19,
  anon_sym_GT_EQ = 20,
  anon_sym_PLUS = 21,
  anon_sym_DASH = 22,
  anon_sym_STAR = 23,
  anon_sym_SLASH = 24,
  anon_sym_PERCENT = 25,
  anon_sym_AMP_AMP = 26,
  anon_sym_PIPE_PIPE = 27,
  anon_sym_BANG = 28,
  anon_sym_if = 29,
  anon_sym_elseif = 30,
  anon_sym_else = 31,
  anon_sym_def = 32,
  sym_source_file = 33,
  sym__top_level_item = 34,
  sym__expression = 35,
  sym_function_call = 36,
  sym_parameter_list = 37,
  sym_named_parameter = 38,
  sym__member_access = 39,
  sym_block = 40,
  sym_list = 41,
  sym__grouped_expression = 42,
  sym__comparison_operator = 43,
  sym__arithmetic_operator = 44,
  sym__logical_operator = 45,
  sym__arithmetic_expression = 46,
  sym__logical_expression = 47,
  sym__comparison_expression = 48,
  sym__statement = 49,
  sym_if_definition = 50,
  sym_function_definition = 51,
  aux_sym_source_file_repeat1 = 52,
  aux_sym_parameter_list_repeat1 = 53,
  aux_sym_block_repeat1 = 54,
  aux_sym_list_repeat1 = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_identifier] = "identifier",
  [sym__line_terminator] = "_line_terminator",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_EQ_EQ] = "operator",
  [anon_sym_BANG_EQ] = "operator",
  [anon_sym_LT] = "operator",
  [anon_sym_GT] = "operator",
  [anon_sym_LT_EQ] = "operator",
  [anon_sym_GT_EQ] = "operator",
  [anon_sym_PLUS] = "operator",
  [anon_sym_DASH] = "operator",
  [anon_sym_STAR] = "operator",
  [anon_sym_SLASH] = "operator",
  [anon_sym_PERCENT] = "operator",
  [anon_sym_AMP_AMP] = "operator",
  [anon_sym_PIPE_PIPE] = "operator",
  [anon_sym_BANG] = "operator",
  [anon_sym_if] = "if",
  [anon_sym_elseif] = "else if",
  [anon_sym_else] = "else",
  [anon_sym_def] = "def",
  [sym_source_file] = "source_file",
  [sym__top_level_item] = "_top_level_item",
  [sym__expression] = "_expression",
  [sym_function_call] = "function_call",
  [sym_parameter_list] = "parameter_list",
  [sym_named_parameter] = "named_parameter",
  [sym__member_access] = "_member_access",
  [sym_block] = "block",
  [sym_list] = "list",
  [sym__grouped_expression] = "_grouped_expression",
  [sym__comparison_operator] = "_comparison_operator",
  [sym__arithmetic_operator] = "_arithmetic_operator",
  [sym__logical_operator] = "_logical_operator",
  [sym__arithmetic_expression] = "_arithmetic_expression",
  [sym__logical_expression] = "_logical_expression",
  [sym__comparison_expression] = "_comparison_expression",
  [sym__statement] = "_statement",
  [sym_if_definition] = "if_definition",
  [sym_function_definition] = "function_definition",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_identifier] = sym_identifier,
  [sym__line_terminator] = sym__line_terminator,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_EQ_EQ,
  [anon_sym_LT] = anon_sym_EQ_EQ,
  [anon_sym_GT] = anon_sym_EQ_EQ,
  [anon_sym_LT_EQ] = anon_sym_EQ_EQ,
  [anon_sym_GT_EQ] = anon_sym_EQ_EQ,
  [anon_sym_PLUS] = anon_sym_EQ_EQ,
  [anon_sym_DASH] = anon_sym_EQ_EQ,
  [anon_sym_STAR] = anon_sym_EQ_EQ,
  [anon_sym_SLASH] = anon_sym_EQ_EQ,
  [anon_sym_PERCENT] = anon_sym_EQ_EQ,
  [anon_sym_AMP_AMP] = anon_sym_EQ_EQ,
  [anon_sym_PIPE_PIPE] = anon_sym_EQ_EQ,
  [anon_sym_BANG] = anon_sym_EQ_EQ,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_elseif] = anon_sym_elseif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_def] = anon_sym_def,
  [sym_source_file] = sym_source_file,
  [sym__top_level_item] = sym__top_level_item,
  [sym__expression] = sym__expression,
  [sym_function_call] = sym_function_call,
  [sym_parameter_list] = sym_parameter_list,
  [sym_named_parameter] = sym_named_parameter,
  [sym__member_access] = sym__member_access,
  [sym_block] = sym_block,
  [sym_list] = sym_list,
  [sym__grouped_expression] = sym__grouped_expression,
  [sym__comparison_operator] = sym__comparison_operator,
  [sym__arithmetic_operator] = sym__arithmetic_operator,
  [sym__logical_operator] = sym__logical_operator,
  [sym__arithmetic_expression] = sym__arithmetic_expression,
  [sym__logical_expression] = sym__logical_expression,
  [sym__comparison_expression] = sym__comparison_expression,
  [sym__statement] = sym__statement,
  [sym_if_definition] = sym_if_definition,
  [sym_function_definition] = sym_function_definition,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__line_terminator] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elseif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__top_level_item] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_named_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym__member_access] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym__grouped_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__comparison_operator] = {
    .visible = false,
    .named = true,
  },
  [sym__arithmetic_operator] = {
    .visible = false,
    .named = true,
  },
  [sym__logical_operator] = {
    .visible = false,
    .named = true,
  },
  [sym__arithmetic_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__logical_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__comparison_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_if_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_body = 1,
  field_condition = 2,
  field_left = 3,
  field_name = 4,
  field_operator = 5,
  field_parameters = 6,
  field_right = 7,
  field_value = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_condition] = "condition",
  [field_left] = "left",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_parameters] = "parameters",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 1},
  [3] = {.index = 4, .length = 3},
  [4] = {.index = 7, .length = 6},
  [5] = {.index = 13, .length = 5},
  [6] = {.index = 18, .length = 9},
  [7] = {.index = 27, .length = 6},
  [8] = {.index = 33, .length = 6},
  [9] = {.index = 39, .length = 3},
  [10] = {.index = 42, .length = 5},
  [11] = {.index = 47, .length = 6},
  [12] = {.index = 53, .length = 10},
  [13] = {.index = 63, .length = 11},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_left, 0, .inherited = true},
    {field_operator, 0, .inherited = true},
    {field_right, 0, .inherited = true},
  [3] =
    {field_name, 0},
  [4] =
    {field_left, 1, .inherited = true},
    {field_operator, 1, .inherited = true},
    {field_right, 1, .inherited = true},
  [7] =
    {field_left, 0, .inherited = true},
    {field_left, 1, .inherited = true},
    {field_operator, 0, .inherited = true},
    {field_operator, 1, .inherited = true},
    {field_right, 0, .inherited = true},
    {field_right, 1, .inherited = true},
  [13] =
    {field_body, 2},
    {field_condition, 1},
    {field_left, 1, .inherited = true},
    {field_operator, 1, .inherited = true},
    {field_right, 1, .inherited = true},
  [18] =
    {field_left, 0},
    {field_left, 0, .inherited = true},
    {field_left, 2, .inherited = true},
    {field_operator, 0, .inherited = true},
    {field_operator, 1},
    {field_operator, 2, .inherited = true},
    {field_right, 0, .inherited = true},
    {field_right, 2},
    {field_right, 2, .inherited = true},
  [27] =
    {field_left, 0, .inherited = true},
    {field_left, 2, .inherited = true},
    {field_operator, 0, .inherited = true},
    {field_operator, 2, .inherited = true},
    {field_right, 0, .inherited = true},
    {field_right, 2, .inherited = true},
  [33] =
    {field_left, 1, .inherited = true},
    {field_left, 2, .inherited = true},
    {field_operator, 1, .inherited = true},
    {field_operator, 2, .inherited = true},
    {field_right, 1, .inherited = true},
    {field_right, 2, .inherited = true},
  [39] =
    {field_body, 3},
    {field_name, 1},
    {field_parameters, 2},
  [42] =
    {field_left, 2, .inherited = true},
    {field_name, 0},
    {field_operator, 2, .inherited = true},
    {field_right, 2, .inherited = true},
    {field_value, 2},
  [47] =
    {field_body, 2},
    {field_body, 4},
    {field_condition, 1},
    {field_left, 1, .inherited = true},
    {field_operator, 1, .inherited = true},
    {field_right, 1, .inherited = true},
  [53] =
    {field_body, 2},
    {field_body, 5},
    {field_condition, 1},
    {field_condition, 4},
    {field_left, 1, .inherited = true},
    {field_left, 4, .inherited = true},
    {field_operator, 1, .inherited = true},
    {field_operator, 4, .inherited = true},
    {field_right, 1, .inherited = true},
    {field_right, 4, .inherited = true},
  [63] =
    {field_body, 2},
    {field_body, 5},
    {field_body, 7},
    {field_condition, 1},
    {field_condition, 4},
    {field_left, 1, .inherited = true},
    {field_left, 4, .inherited = true},
    {field_operator, 1, .inherited = true},
    {field_operator, 4, .inherited = true},
    {field_right, 1, .inherited = true},
    {field_right, 4, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 23,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 29,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 35,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 33,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 45,
  [47] = 47,
  [48] = 44,
  [49] = 45,
  [50] = 44,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 55,
  [58] = 56,
  [59] = 59,
  [60] = 55,
  [61] = 56,
  [62] = 55,
  [63] = 56,
  [64] = 55,
  [65] = 56,
  [66] = 43,
  [67] = 45,
  [68] = 44,
  [69] = 44,
  [70] = 47,
  [71] = 45,
  [72] = 72,
  [73] = 53,
  [74] = 51,
  [75] = 52,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 83,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 88,
  [90] = 86,
  [91] = 91,
  [92] = 87,
  [93] = 93,
  [94] = 94,
  [95] = 93,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(24);
      if (lookahead == '!') ADVANCE(62);
      if (lookahead == '%') ADVANCE(59);
      if (lookahead == '&') ADVANCE(1);
      if (lookahead == '(') ADVANCE(40);
      if (lookahead == ')') ADVANCE(42);
      if (lookahead == '*') ADVANCE(57);
      if (lookahead == '+') ADVANCE(55);
      if (lookahead == ',') ADVANCE(41);
      if (lookahead == '-') ADVANCE(56);
      if (lookahead == '.') ADVANCE(44);
      if (lookahead == '/') ADVANCE(58);
      if (lookahead == ':') ADVANCE(43);
      if (lookahead == ';') ADVANCE(39);
      if (lookahead == '<') ADVANCE(51);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == '>') ADVANCE(52);
      if (lookahead == '[') ADVANCE(47);
      if (lookahead == ']') ADVANCE(48);
      if (lookahead == 'd') ADVANCE(31);
      if (lookahead == 'e') ADVANCE(34);
      if (lookahead == 'i') ADVANCE(32);
      if (lookahead == '{') ADVANCE(45);
      if (lookahead == '|') ADVANCE(19);
      if (lookahead == '}') ADVANCE(46);
      if (lookahead == '"' ||
          lookahead == '\'') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 1:
      if (lookahead == '&') ADVANCE(60);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(40);
      if (lookahead == ')') ADVANCE(42);
      if (lookahead == '.') ADVANCE(44);
      if (lookahead == '[') ADVANCE(47);
      if (lookahead == '"' ||
          lookahead == '\'') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(25);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == 'd') ADVANCE(10);
      if (lookahead == 'e') ADVANCE(15);
      if (lookahead == 'i') ADVANCE(12);
      if (lookahead == '}') ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == 'd') ADVANCE(10);
      if (lookahead == 'e') ADVANCE(16);
      if (lookahead == 'i') ADVANCE(12);
      if (lookahead == '}') ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(49);
      END_STATE();
    case 7:
      if (lookahead == '\\') ADVANCE(21);
      if (lookahead == '"' ||
          lookahead == '\'') ADVANCE(26);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'f') ADVANCE(65);
      END_STATE();
    case 12:
      if (lookahead == 'f') ADVANCE(63);
      END_STATE();
    case 13:
      if (lookahead == 'f') ADVANCE(70);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(11);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 17:
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(9);
      END_STATE();
    case 19:
      if (lookahead == '|') ADVANCE(61);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 21:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 22:
      if (eof) ADVANCE(24);
      if (lookahead == '!') ADVANCE(62);
      if (lookahead == '%') ADVANCE(59);
      if (lookahead == '&') ADVANCE(1);
      if (lookahead == '(') ADVANCE(40);
      if (lookahead == ')') ADVANCE(42);
      if (lookahead == '*') ADVANCE(57);
      if (lookahead == '+') ADVANCE(55);
      if (lookahead == ',') ADVANCE(41);
      if (lookahead == '-') ADVANCE(56);
      if (lookahead == '.') ADVANCE(44);
      if (lookahead == '/') ADVANCE(58);
      if (lookahead == '<') ADVANCE(51);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == '>') ADVANCE(52);
      if (lookahead == '[') ADVANCE(47);
      if (lookahead == ']') ADVANCE(48);
      if (lookahead == 'd') ADVANCE(31);
      if (lookahead == 'i') ADVANCE(32);
      if (lookahead == '{') ADVANCE(45);
      if (lookahead == '|') ADVANCE(19);
      if (lookahead == '"' ||
          lookahead == '\'') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(22)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 23:
      if (eof) ADVANCE(24);
      if (lookahead == '(') ADVANCE(40);
      if (lookahead == '.') ADVANCE(44);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '[') ADVANCE(47);
      if (lookahead == 'd') ADVANCE(31);
      if (lookahead == 'e') ADVANCE(35);
      if (lookahead == 'i') ADVANCE(32);
      if (lookahead == '"' ||
          lookahead == '\'') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(23)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__line_terminator);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(53);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(54);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(25);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(50);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_elseif);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_else);
      if (lookahead == ' ') ADVANCE(14);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_else);
      if (lookahead == ' ') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_def);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_def);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 22},
  [2] = {.lex_state = 22},
  [3] = {.lex_state = 22},
  [4] = {.lex_state = 22},
  [5] = {.lex_state = 22},
  [6] = {.lex_state = 22},
  [7] = {.lex_state = 22},
  [8] = {.lex_state = 22},
  [9] = {.lex_state = 22},
  [10] = {.lex_state = 22},
  [11] = {.lex_state = 22},
  [12] = {.lex_state = 22},
  [13] = {.lex_state = 22},
  [14] = {.lex_state = 22},
  [15] = {.lex_state = 22},
  [16] = {.lex_state = 22},
  [17] = {.lex_state = 22},
  [18] = {.lex_state = 22},
  [19] = {.lex_state = 22},
  [20] = {.lex_state = 22},
  [21] = {.lex_state = 22},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 23},
  [47] = {.lex_state = 23},
  [48] = {.lex_state = 23},
  [49] = {.lex_state = 22},
  [50] = {.lex_state = 22},
  [51] = {.lex_state = 22},
  [52] = {.lex_state = 22},
  [53] = {.lex_state = 22},
  [54] = {.lex_state = 22},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 4},
  [57] = {.lex_state = 4},
  [58] = {.lex_state = 4},
  [59] = {.lex_state = 4},
  [60] = {.lex_state = 4},
  [61] = {.lex_state = 4},
  [62] = {.lex_state = 4},
  [63] = {.lex_state = 4},
  [64] = {.lex_state = 4},
  [65] = {.lex_state = 4},
  [66] = {.lex_state = 4},
  [67] = {.lex_state = 4},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 5},
  [70] = {.lex_state = 5},
  [71] = {.lex_state = 5},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 4},
  [74] = {.lex_state = 4},
  [75] = {.lex_state = 4},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 2},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym__line_terminator] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_elseif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(94),
    [sym__top_level_item] = STATE(54),
    [sym__expression] = STATE(19),
    [sym_function_call] = STATE(19),
    [sym__member_access] = STATE(10),
    [sym_list] = STATE(19),
    [sym__grouped_expression] = STATE(11),
    [sym__arithmetic_expression] = STATE(7),
    [sym__logical_expression] = STATE(13),
    [sym__comparison_expression] = STATE(14),
    [sym__statement] = STATE(54),
    [sym_if_definition] = STATE(54),
    [sym_function_definition] = STATE(54),
    [aux_sym_source_file_repeat1] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_string] = ACTIONS(7),
    [sym_number] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_def] = ACTIONS(19),
  },
  [2] = {
    [sym__comparison_operator] = STATE(40),
    [sym__arithmetic_operator] = STATE(39),
    [sym__logical_operator] = STATE(31),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_comment] = ACTIONS(21),
    [sym_string] = ACTIONS(21),
    [sym_number] = ACTIONS(21),
    [sym_identifier] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(25),
    [anon_sym_BANG_EQ] = ACTIONS(25),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_LT_EQ] = ACTIONS(25),
    [anon_sym_GT_EQ] = ACTIONS(25),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(29),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_PERCENT] = ACTIONS(29),
    [anon_sym_AMP_AMP] = ACTIONS(33),
    [anon_sym_PIPE_PIPE] = ACTIONS(33),
    [anon_sym_BANG] = ACTIONS(35),
    [anon_sym_if] = ACTIONS(23),
    [anon_sym_def] = ACTIONS(23),
  },
  [3] = {
    [sym__comparison_operator] = STATE(40),
    [sym__arithmetic_operator] = STATE(39),
    [sym__logical_operator] = STATE(31),
    [ts_builtin_sym_end] = ACTIONS(37),
    [sym_comment] = ACTIONS(37),
    [sym_string] = ACTIONS(37),
    [sym_number] = ACTIONS(37),
    [sym_identifier] = ACTIONS(39),
    [anon_sym_LPAREN] = ACTIONS(37),
    [anon_sym_COMMA] = ACTIONS(37),
    [anon_sym_RPAREN] = ACTIONS(37),
    [anon_sym_DOT] = ACTIONS(37),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(37),
    [anon_sym_RBRACK] = ACTIONS(37),
    [anon_sym_EQ_EQ] = ACTIONS(37),
    [anon_sym_BANG_EQ] = ACTIONS(37),
    [anon_sym_LT] = ACTIONS(39),
    [anon_sym_GT] = ACTIONS(39),
    [anon_sym_LT_EQ] = ACTIONS(37),
    [anon_sym_GT_EQ] = ACTIONS(37),
    [anon_sym_PLUS] = ACTIONS(37),
    [anon_sym_DASH] = ACTIONS(37),
    [anon_sym_STAR] = ACTIONS(37),
    [anon_sym_SLASH] = ACTIONS(39),
    [anon_sym_PERCENT] = ACTIONS(37),
    [anon_sym_AMP_AMP] = ACTIONS(37),
    [anon_sym_PIPE_PIPE] = ACTIONS(37),
    [anon_sym_BANG] = ACTIONS(39),
    [anon_sym_if] = ACTIONS(39),
    [anon_sym_def] = ACTIONS(39),
  },
  [4] = {
    [sym__comparison_operator] = STATE(40),
    [sym__arithmetic_operator] = STATE(39),
    [sym__logical_operator] = STATE(31),
    [ts_builtin_sym_end] = ACTIONS(41),
    [sym_comment] = ACTIONS(41),
    [sym_string] = ACTIONS(41),
    [sym_number] = ACTIONS(41),
    [sym_identifier] = ACTIONS(43),
    [anon_sym_LPAREN] = ACTIONS(41),
    [anon_sym_COMMA] = ACTIONS(41),
    [anon_sym_RPAREN] = ACTIONS(41),
    [anon_sym_DOT] = ACTIONS(41),
    [anon_sym_LBRACE] = ACTIONS(41),
    [anon_sym_LBRACK] = ACTIONS(41),
    [anon_sym_RBRACK] = ACTIONS(41),
    [anon_sym_EQ_EQ] = ACTIONS(41),
    [anon_sym_BANG_EQ] = ACTIONS(41),
    [anon_sym_LT] = ACTIONS(43),
    [anon_sym_GT] = ACTIONS(43),
    [anon_sym_LT_EQ] = ACTIONS(41),
    [anon_sym_GT_EQ] = ACTIONS(41),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(41),
    [anon_sym_STAR] = ACTIONS(41),
    [anon_sym_SLASH] = ACTIONS(43),
    [anon_sym_PERCENT] = ACTIONS(41),
    [anon_sym_AMP_AMP] = ACTIONS(41),
    [anon_sym_PIPE_PIPE] = ACTIONS(41),
    [anon_sym_BANG] = ACTIONS(43),
    [anon_sym_if] = ACTIONS(43),
    [anon_sym_def] = ACTIONS(43),
  },
  [5] = {
    [sym__comparison_operator] = STATE(40),
    [sym__arithmetic_operator] = STATE(39),
    [sym__logical_operator] = STATE(31),
    [ts_builtin_sym_end] = ACTIONS(45),
    [sym_comment] = ACTIONS(45),
    [sym_string] = ACTIONS(45),
    [sym_number] = ACTIONS(45),
    [sym_identifier] = ACTIONS(47),
    [anon_sym_LPAREN] = ACTIONS(45),
    [anon_sym_COMMA] = ACTIONS(45),
    [anon_sym_RPAREN] = ACTIONS(45),
    [anon_sym_DOT] = ACTIONS(45),
    [anon_sym_LBRACE] = ACTIONS(45),
    [anon_sym_LBRACK] = ACTIONS(45),
    [anon_sym_RBRACK] = ACTIONS(45),
    [anon_sym_EQ_EQ] = ACTIONS(45),
    [anon_sym_BANG_EQ] = ACTIONS(45),
    [anon_sym_LT] = ACTIONS(47),
    [anon_sym_GT] = ACTIONS(47),
    [anon_sym_LT_EQ] = ACTIONS(45),
    [anon_sym_GT_EQ] = ACTIONS(45),
    [anon_sym_PLUS] = ACTIONS(45),
    [anon_sym_DASH] = ACTIONS(45),
    [anon_sym_STAR] = ACTIONS(45),
    [anon_sym_SLASH] = ACTIONS(47),
    [anon_sym_PERCENT] = ACTIONS(45),
    [anon_sym_AMP_AMP] = ACTIONS(45),
    [anon_sym_PIPE_PIPE] = ACTIONS(45),
    [anon_sym_BANG] = ACTIONS(47),
    [anon_sym_if] = ACTIONS(47),
    [anon_sym_def] = ACTIONS(47),
  },
  [6] = {
    [sym_parameter_list] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(49),
    [sym_comment] = ACTIONS(49),
    [sym_string] = ACTIONS(49),
    [sym_number] = ACTIONS(49),
    [sym_identifier] = ACTIONS(51),
    [anon_sym_LPAREN] = ACTIONS(53),
    [anon_sym_COMMA] = ACTIONS(49),
    [anon_sym_RPAREN] = ACTIONS(49),
    [anon_sym_DOT] = ACTIONS(49),
    [anon_sym_LBRACE] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(49),
    [anon_sym_RBRACK] = ACTIONS(49),
    [anon_sym_EQ_EQ] = ACTIONS(49),
    [anon_sym_BANG_EQ] = ACTIONS(49),
    [anon_sym_LT] = ACTIONS(51),
    [anon_sym_GT] = ACTIONS(51),
    [anon_sym_LT_EQ] = ACTIONS(49),
    [anon_sym_GT_EQ] = ACTIONS(49),
    [anon_sym_PLUS] = ACTIONS(49),
    [anon_sym_DASH] = ACTIONS(49),
    [anon_sym_STAR] = ACTIONS(49),
    [anon_sym_SLASH] = ACTIONS(51),
    [anon_sym_PERCENT] = ACTIONS(49),
    [anon_sym_AMP_AMP] = ACTIONS(49),
    [anon_sym_PIPE_PIPE] = ACTIONS(49),
    [anon_sym_BANG] = ACTIONS(51),
    [anon_sym_if] = ACTIONS(51),
    [anon_sym_def] = ACTIONS(51),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(57), 7,
      sym_identifier,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_BANG,
      anon_sym_if,
      anon_sym_def,
    ACTIONS(55), 21,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [33] = 2,
    ACTIONS(61), 7,
      sym_identifier,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_BANG,
      anon_sym_if,
      anon_sym_def,
    ACTIONS(59), 21,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [66] = 2,
    ACTIONS(65), 7,
      sym_identifier,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_BANG,
      anon_sym_if,
      anon_sym_def,
    ACTIONS(63), 21,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [99] = 2,
    ACTIONS(57), 7,
      sym_identifier,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_BANG,
      anon_sym_if,
      anon_sym_def,
    ACTIONS(55), 21,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [132] = 2,
    ACTIONS(57), 7,
      sym_identifier,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_BANG,
      anon_sym_if,
      anon_sym_def,
    ACTIONS(55), 21,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [165] = 2,
    ACTIONS(69), 7,
      sym_identifier,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_BANG,
      anon_sym_if,
      anon_sym_def,
    ACTIONS(67), 21,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [198] = 2,
    ACTIONS(57), 7,
      sym_identifier,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_BANG,
      anon_sym_if,
      anon_sym_def,
    ACTIONS(55), 21,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [231] = 2,
    ACTIONS(57), 7,
      sym_identifier,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_BANG,
      anon_sym_if,
      anon_sym_def,
    ACTIONS(55), 21,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [264] = 2,
    ACTIONS(73), 7,
      sym_identifier,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_BANG,
      anon_sym_if,
      anon_sym_def,
    ACTIONS(71), 21,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [297] = 2,
    ACTIONS(77), 7,
      sym_identifier,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_BANG,
      anon_sym_if,
      anon_sym_def,
    ACTIONS(75), 21,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [330] = 2,
    ACTIONS(81), 7,
      sym_identifier,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_BANG,
      anon_sym_if,
      anon_sym_def,
    ACTIONS(79), 21,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [363] = 2,
    ACTIONS(85), 7,
      sym_identifier,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_BANG,
      anon_sym_if,
      anon_sym_def,
    ACTIONS(83), 21,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DOT,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [396] = 11,
    ACTIONS(31), 1,
      anon_sym_SLASH,
    ACTIONS(35), 1,
      anon_sym_BANG,
    STATE(31), 1,
      sym__logical_operator,
    STATE(39), 1,
      sym__arithmetic_operator,
    STATE(40), 1,
      sym__comparison_operator,
    ACTIONS(27), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
    ACTIONS(89), 3,
      sym_identifier,
      anon_sym_if,
      anon_sym_def,
    ACTIONS(25), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(29), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_PERCENT,
    ACTIONS(87), 7,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
  [446] = 17,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    ACTIONS(93), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(102), 1,
      anon_sym_LPAREN,
    ACTIONS(105), 1,
      anon_sym_DOT,
    ACTIONS(108), 1,
      anon_sym_LBRACK,
    ACTIONS(111), 1,
      anon_sym_if,
    ACTIONS(114), 1,
      anon_sym_def,
    STATE(7), 1,
      sym__arithmetic_expression,
    STATE(10), 1,
      sym__member_access,
    STATE(11), 1,
      sym__grouped_expression,
    STATE(13), 1,
      sym__logical_expression,
    STATE(14), 1,
      sym__comparison_expression,
    STATE(20), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(96), 2,
      sym_string,
      sym_number,
    STATE(19), 3,
      sym__expression,
      sym_function_call,
      sym_list,
    STATE(54), 4,
      sym__top_level_item,
      sym__statement,
      sym_if_definition,
      sym_function_definition,
  [504] = 17,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_if,
    ACTIONS(19), 1,
      anon_sym_def,
    ACTIONS(117), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      sym__arithmetic_expression,
    STATE(10), 1,
      sym__member_access,
    STATE(11), 1,
      sym__grouped_expression,
    STATE(13), 1,
      sym__logical_expression,
    STATE(14), 1,
      sym__comparison_expression,
    STATE(20), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(7), 2,
      sym_string,
      sym_number,
    STATE(19), 3,
      sym__expression,
      sym_function_call,
      sym_list,
    STATE(54), 4,
      sym__top_level_item,
      sym__statement,
      sym_if_definition,
      sym_function_definition,
  [562] = 11,
    ACTIONS(35), 1,
      anon_sym_BANG,
    ACTIONS(119), 1,
      anon_sym_COMMA,
    ACTIONS(121), 1,
      anon_sym_RBRACK,
    STATE(31), 1,
      sym__logical_operator,
    STATE(39), 1,
      sym__arithmetic_operator,
    STATE(40), 1,
      sym__comparison_operator,
    STATE(77), 1,
      aux_sym_list_repeat1,
    ACTIONS(27), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
    ACTIONS(25), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(29), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [605] = 10,
    ACTIONS(35), 1,
      anon_sym_BANG,
    ACTIONS(123), 1,
      anon_sym_LBRACE,
    STATE(31), 1,
      sym__logical_operator,
    STATE(39), 1,
      sym__arithmetic_operator,
    STATE(40), 1,
      sym__comparison_operator,
    STATE(66), 1,
      sym_block,
    ACTIONS(27), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
    ACTIONS(25), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(29), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [645] = 9,
    ACTIONS(35), 1,
      anon_sym_BANG,
    STATE(31), 1,
      sym__logical_operator,
    STATE(39), 1,
      sym__arithmetic_operator,
    STATE(40), 1,
      sym__comparison_operator,
    ACTIONS(27), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
    ACTIONS(125), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    ACTIONS(25), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(29), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [683] = 10,
    ACTIONS(35), 1,
      anon_sym_BANG,
    ACTIONS(127), 1,
      anon_sym_LBRACE,
    STATE(31), 1,
      sym__logical_operator,
    STATE(39), 1,
      sym__arithmetic_operator,
    STATE(40), 1,
      sym__comparison_operator,
    STATE(43), 1,
      sym_block,
    ACTIONS(27), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
    ACTIONS(25), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(29), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [723] = 9,
    ACTIONS(35), 1,
      anon_sym_BANG,
    STATE(31), 1,
      sym__logical_operator,
    STATE(39), 1,
      sym__arithmetic_operator,
    STATE(40), 1,
      sym__comparison_operator,
    ACTIONS(27), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
    ACTIONS(129), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(25), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(29), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [761] = 9,
    ACTIONS(35), 1,
      anon_sym_BANG,
    ACTIONS(131), 1,
      anon_sym_RPAREN,
    STATE(31), 1,
      sym__logical_operator,
    STATE(39), 1,
      sym__arithmetic_operator,
    STATE(40), 1,
      sym__comparison_operator,
    ACTIONS(27), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
    ACTIONS(25), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(29), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [798] = 8,
    ACTIONS(35), 1,
      anon_sym_BANG,
    STATE(31), 1,
      sym__logical_operator,
    STATE(39), 1,
      sym__arithmetic_operator,
    STATE(40), 1,
      sym__comparison_operator,
    ACTIONS(27), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
    ACTIONS(25), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(29), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [832] = 4,
    ACTIONS(133), 1,
      anon_sym_LBRACE,
    STATE(47), 1,
      sym_block,
    ACTIONS(57), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG,
    ACTIONS(55), 11,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [857] = 4,
    ACTIONS(135), 1,
      anon_sym_LBRACE,
    STATE(70), 1,
      sym_block,
    ACTIONS(57), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG,
    ACTIONS(55), 11,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [882] = 11,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(7), 1,
      sym__arithmetic_expression,
    STATE(10), 1,
      sym__member_access,
    STATE(11), 1,
      sym__grouped_expression,
    STATE(13), 1,
      sym__logical_expression,
    STATE(14), 1,
      sym__comparison_expression,
    ACTIONS(137), 2,
      sym_string,
      sym_number,
    STATE(3), 3,
      sym__expression,
      sym_function_call,
      sym_list,
  [919] = 11,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(7), 1,
      sym__arithmetic_expression,
    STATE(10), 1,
      sym__member_access,
    STATE(11), 1,
      sym__grouped_expression,
    STATE(13), 1,
      sym__logical_expression,
    STATE(14), 1,
      sym__comparison_expression,
    ACTIONS(141), 2,
      sym_string,
      sym_number,
    STATE(24), 3,
      sym__expression,
      sym_function_call,
      sym_list,
  [956] = 11,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(7), 1,
      sym__arithmetic_expression,
    STATE(10), 1,
      sym__member_access,
    STATE(11), 1,
      sym__grouped_expression,
    STATE(13), 1,
      sym__logical_expression,
    STATE(30), 1,
      sym__comparison_expression,
    ACTIONS(143), 2,
      sym_string,
      sym_number,
    STATE(28), 3,
      sym__expression,
      sym_function_call,
      sym_list,
  [993] = 11,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(7), 1,
      sym__arithmetic_expression,
    STATE(10), 1,
      sym__member_access,
    STATE(11), 1,
      sym__grouped_expression,
    STATE(13), 1,
      sym__logical_expression,
    STATE(14), 1,
      sym__comparison_expression,
    ACTIONS(145), 2,
      sym_string,
      sym_number,
    STATE(27), 3,
      sym__expression,
      sym_function_call,
      sym_list,
  [1030] = 11,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(7), 1,
      sym__arithmetic_expression,
    STATE(10), 1,
      sym__member_access,
    STATE(11), 1,
      sym__grouped_expression,
    STATE(13), 1,
      sym__logical_expression,
    STATE(14), 1,
      sym__comparison_expression,
    ACTIONS(147), 2,
      sym_string,
      sym_number,
    STATE(25), 3,
      sym__expression,
      sym_function_call,
      sym_list,
  [1067] = 11,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(7), 1,
      sym__arithmetic_expression,
    STATE(10), 1,
      sym__member_access,
    STATE(11), 1,
      sym__grouped_expression,
    STATE(13), 1,
      sym__logical_expression,
    STATE(14), 1,
      sym__comparison_expression,
    ACTIONS(149), 2,
      sym_string,
      sym_number,
    STATE(22), 3,
      sym__expression,
      sym_function_call,
      sym_list,
  [1104] = 11,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(7), 1,
      sym__arithmetic_expression,
    STATE(10), 1,
      sym__member_access,
    STATE(11), 1,
      sym__grouped_expression,
    STATE(13), 1,
      sym__logical_expression,
    STATE(14), 1,
      sym__comparison_expression,
    ACTIONS(151), 2,
      sym_string,
      sym_number,
    STATE(23), 3,
      sym__expression,
      sym_function_call,
      sym_list,
  [1141] = 11,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(7), 1,
      sym__arithmetic_expression,
    STATE(10), 1,
      sym__member_access,
    STATE(11), 1,
      sym__grouped_expression,
    STATE(13), 1,
      sym__logical_expression,
    STATE(14), 1,
      sym__comparison_expression,
    ACTIONS(153), 2,
      sym_string,
      sym_number,
    STATE(26), 3,
      sym__expression,
      sym_function_call,
      sym_list,
  [1178] = 11,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(7), 1,
      sym__arithmetic_expression,
    STATE(10), 1,
      sym__member_access,
    STATE(11), 1,
      sym__grouped_expression,
    STATE(13), 1,
      sym__logical_expression,
    STATE(14), 1,
      sym__comparison_expression,
    ACTIONS(155), 2,
      sym_string,
      sym_number,
    STATE(4), 3,
      sym__expression,
      sym_function_call,
      sym_list,
  [1215] = 11,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(7), 1,
      sym__arithmetic_expression,
    STATE(10), 1,
      sym__member_access,
    STATE(11), 1,
      sym__grouped_expression,
    STATE(13), 1,
      sym__logical_expression,
    STATE(14), 1,
      sym__comparison_expression,
    ACTIONS(157), 2,
      sym_string,
      sym_number,
    STATE(5), 3,
      sym__expression,
      sym_function_call,
      sym_list,
  [1252] = 11,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(7), 1,
      sym__arithmetic_expression,
    STATE(10), 1,
      sym__member_access,
    STATE(11), 1,
      sym__grouped_expression,
    STATE(13), 1,
      sym__logical_expression,
    STATE(14), 1,
      sym__comparison_expression,
    ACTIONS(159), 2,
      sym_string,
      sym_number,
    STATE(2), 3,
      sym__expression,
      sym_function_call,
      sym_list,
  [1289] = 11,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(7), 1,
      sym__arithmetic_expression,
    STATE(10), 1,
      sym__member_access,
    STATE(11), 1,
      sym__grouped_expression,
    STATE(13), 1,
      sym__logical_expression,
    STATE(29), 1,
      sym__comparison_expression,
    ACTIONS(143), 2,
      sym_string,
      sym_number,
    STATE(28), 3,
      sym__expression,
      sym_function_call,
      sym_list,
  [1326] = 4,
    ACTIONS(165), 1,
      anon_sym_elseif,
    ACTIONS(167), 1,
      anon_sym_else,
    ACTIONS(163), 3,
      sym_identifier,
      anon_sym_if,
      anon_sym_def,
    ACTIONS(161), 7,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
  [1347] = 2,
    ACTIONS(171), 4,
      sym_identifier,
      anon_sym_if,
      anon_sym_else,
      anon_sym_def,
    ACTIONS(169), 8,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_elseif,
  [1364] = 2,
    ACTIONS(175), 4,
      sym_identifier,
      anon_sym_if,
      anon_sym_else,
      anon_sym_def,
    ACTIONS(173), 8,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_elseif,
  [1381] = 2,
    ACTIONS(175), 4,
      sym_identifier,
      anon_sym_if,
      anon_sym_else,
      anon_sym_def,
    ACTIONS(173), 7,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
  [1397] = 3,
    ACTIONS(181), 1,
      anon_sym_else,
    ACTIONS(179), 3,
      sym_identifier,
      anon_sym_if,
      anon_sym_def,
    ACTIONS(177), 7,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
  [1415] = 2,
    ACTIONS(171), 4,
      sym_identifier,
      anon_sym_if,
      anon_sym_else,
      anon_sym_def,
    ACTIONS(169), 7,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
  [1431] = 2,
    ACTIONS(175), 3,
      sym_identifier,
      anon_sym_if,
      anon_sym_def,
    ACTIONS(173), 7,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
  [1446] = 2,
    ACTIONS(171), 3,
      sym_identifier,
      anon_sym_if,
      anon_sym_def,
    ACTIONS(169), 7,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
  [1461] = 2,
    ACTIONS(185), 3,
      sym_identifier,
      anon_sym_if,
      anon_sym_def,
    ACTIONS(183), 7,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
  [1476] = 2,
    ACTIONS(189), 3,
      sym_identifier,
      anon_sym_if,
      anon_sym_def,
    ACTIONS(187), 7,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
  [1491] = 2,
    ACTIONS(193), 3,
      sym_identifier,
      anon_sym_if,
      anon_sym_def,
    ACTIONS(191), 7,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
  [1506] = 2,
    ACTIONS(197), 3,
      sym_identifier,
      anon_sym_if,
      anon_sym_def,
    ACTIONS(195), 7,
      ts_builtin_sym_end,
      sym_comment,
      sym_string,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_DOT,
      anon_sym_LBRACK,
  [1521] = 5,
    ACTIONS(199), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_RBRACE,
    ACTIONS(203), 1,
      anon_sym_if,
    ACTIONS(205), 1,
      anon_sym_def,
    STATE(59), 4,
      sym__statement,
      sym_if_definition,
      sym_function_definition,
      aux_sym_block_repeat1,
  [1540] = 5,
    ACTIONS(203), 1,
      anon_sym_if,
    ACTIONS(205), 1,
      anon_sym_def,
    ACTIONS(207), 1,
      sym_comment,
    ACTIONS(209), 1,
      anon_sym_RBRACE,
    STATE(55), 4,
      sym__statement,
      sym_if_definition,
      sym_function_definition,
      aux_sym_block_repeat1,
  [1559] = 5,
    ACTIONS(199), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_if,
    ACTIONS(205), 1,
      anon_sym_def,
    ACTIONS(211), 1,
      anon_sym_RBRACE,
    STATE(59), 4,
      sym__statement,
      sym_if_definition,
      sym_function_definition,
      aux_sym_block_repeat1,
  [1578] = 5,
    ACTIONS(203), 1,
      anon_sym_if,
    ACTIONS(205), 1,
      anon_sym_def,
    ACTIONS(213), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_RBRACE,
    STATE(57), 4,
      sym__statement,
      sym_if_definition,
      sym_function_definition,
      aux_sym_block_repeat1,
  [1597] = 5,
    ACTIONS(217), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_RBRACE,
    ACTIONS(222), 1,
      anon_sym_if,
    ACTIONS(225), 1,
      anon_sym_def,
    STATE(59), 4,
      sym__statement,
      sym_if_definition,
      sym_function_definition,
      aux_sym_block_repeat1,
  [1616] = 5,
    ACTIONS(199), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_if,
    ACTIONS(205), 1,
      anon_sym_def,
    ACTIONS(228), 1,
      anon_sym_RBRACE,
    STATE(59), 4,
      sym__statement,
      sym_if_definition,
      sym_function_definition,
      aux_sym_block_repeat1,
  [1635] = 5,
    ACTIONS(203), 1,
      anon_sym_if,
    ACTIONS(205), 1,
      anon_sym_def,
    ACTIONS(230), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_RBRACE,
    STATE(60), 4,
      sym__statement,
      sym_if_definition,
      sym_function_definition,
      aux_sym_block_repeat1,
  [1654] = 5,
    ACTIONS(199), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_if,
    ACTIONS(205), 1,
      anon_sym_def,
    ACTIONS(234), 1,
      anon_sym_RBRACE,
    STATE(59), 4,
      sym__statement,
      sym_if_definition,
      sym_function_definition,
      aux_sym_block_repeat1,
  [1673] = 5,
    ACTIONS(203), 1,
      anon_sym_if,
    ACTIONS(205), 1,
      anon_sym_def,
    ACTIONS(236), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_RBRACE,
    STATE(62), 4,
      sym__statement,
      sym_if_definition,
      sym_function_definition,
      aux_sym_block_repeat1,
  [1692] = 5,
    ACTIONS(199), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_if,
    ACTIONS(205), 1,
      anon_sym_def,
    ACTIONS(240), 1,
      anon_sym_RBRACE,
    STATE(59), 4,
      sym__statement,
      sym_if_definition,
      sym_function_definition,
      aux_sym_block_repeat1,
  [1711] = 5,
    ACTIONS(203), 1,
      anon_sym_if,
    ACTIONS(205), 1,
      anon_sym_def,
    ACTIONS(242), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_RBRACE,
    STATE(64), 4,
      sym__statement,
      sym_if_definition,
      sym_function_definition,
      aux_sym_block_repeat1,
  [1730] = 3,
    ACTIONS(246), 1,
      anon_sym_elseif,
    ACTIONS(248), 1,
      anon_sym_else,
    ACTIONS(161), 4,
      sym_comment,
      anon_sym_RBRACE,
      anon_sym_if,
      anon_sym_def,
  [1743] = 2,
    ACTIONS(175), 1,
      anon_sym_else,
    ACTIONS(173), 5,
      sym_comment,
      anon_sym_RBRACE,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_def,
  [1754] = 2,
    ACTIONS(171), 1,
      anon_sym_else,
    ACTIONS(169), 5,
      sym_comment,
      anon_sym_RBRACE,
      anon_sym_if,
      anon_sym_elseif,
      anon_sym_def,
  [1765] = 1,
    ACTIONS(169), 5,
      sym_comment,
      anon_sym_RBRACE,
      anon_sym_if,
      anon_sym_else,
      anon_sym_def,
  [1773] = 2,
    ACTIONS(250), 1,
      anon_sym_else,
    ACTIONS(177), 4,
      sym_comment,
      anon_sym_RBRACE,
      anon_sym_if,
      anon_sym_def,
  [1783] = 1,
    ACTIONS(173), 5,
      sym_comment,
      anon_sym_RBRACE,
      anon_sym_if,
      anon_sym_else,
      anon_sym_def,
  [1791] = 4,
    ACTIONS(252), 1,
      anon_sym_COMMA,
    ACTIONS(254), 1,
      anon_sym_RPAREN,
    ACTIONS(256), 1,
      anon_sym_COLON,
    STATE(80), 1,
      aux_sym_parameter_list_repeat1,
  [1804] = 1,
    ACTIONS(191), 4,
      sym_comment,
      anon_sym_RBRACE,
      anon_sym_if,
      anon_sym_def,
  [1811] = 1,
    ACTIONS(183), 4,
      sym_comment,
      anon_sym_RBRACE,
      anon_sym_if,
      anon_sym_def,
  [1818] = 1,
    ACTIONS(187), 4,
      sym_comment,
      anon_sym_RBRACE,
      anon_sym_if,
      anon_sym_def,
  [1825] = 3,
    ACTIONS(258), 1,
      anon_sym_COMMA,
    ACTIONS(261), 1,
      anon_sym_RBRACK,
    STATE(76), 1,
      aux_sym_list_repeat1,
  [1835] = 3,
    ACTIONS(119), 1,
      anon_sym_COMMA,
    ACTIONS(263), 1,
      anon_sym_RBRACK,
    STATE(76), 1,
      aux_sym_list_repeat1,
  [1845] = 3,
    ACTIONS(252), 1,
      anon_sym_COMMA,
    ACTIONS(254), 1,
      anon_sym_RPAREN,
    STATE(80), 1,
      aux_sym_parameter_list_repeat1,
  [1855] = 3,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    ACTIONS(268), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      aux_sym_parameter_list_repeat1,
  [1865] = 3,
    ACTIONS(252), 1,
      anon_sym_COMMA,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      aux_sym_parameter_list_repeat1,
  [1875] = 2,
    ACTIONS(256), 1,
      anon_sym_COLON,
    ACTIONS(268), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1883] = 3,
    ACTIONS(272), 1,
      sym_identifier,
    ACTIONS(274), 1,
      anon_sym_RPAREN,
    STATE(78), 1,
      sym_named_parameter,
  [1893] = 2,
    ACTIONS(276), 1,
      anon_sym_LBRACE,
    STATE(53), 1,
      sym_block,
  [1900] = 2,
    ACTIONS(123), 1,
      anon_sym_LBRACE,
    STATE(73), 1,
      sym_block,
  [1907] = 2,
    ACTIONS(278), 1,
      sym_identifier,
    STATE(91), 1,
      sym_named_parameter,
  [1914] = 2,
    ACTIONS(123), 1,
      anon_sym_LBRACE,
    STATE(74), 1,
      sym_block,
  [1921] = 2,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    STATE(83), 1,
      sym_parameter_list,
  [1928] = 2,
    ACTIONS(123), 1,
      anon_sym_LBRACE,
    STATE(75), 1,
      sym_block,
  [1935] = 2,
    ACTIONS(276), 1,
      anon_sym_LBRACE,
    STATE(52), 1,
      sym_block,
  [1942] = 2,
    ACTIONS(276), 1,
      anon_sym_LBRACE,
    STATE(51), 1,
      sym_block,
  [1949] = 1,
    ACTIONS(268), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1954] = 2,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    STATE(84), 1,
      sym_parameter_list,
  [1961] = 1,
    ACTIONS(280), 1,
      sym_identifier,
  [1965] = 1,
    ACTIONS(282), 1,
      ts_builtin_sym_end,
  [1969] = 1,
    ACTIONS(284), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 33,
  [SMALL_STATE(9)] = 66,
  [SMALL_STATE(10)] = 99,
  [SMALL_STATE(11)] = 132,
  [SMALL_STATE(12)] = 165,
  [SMALL_STATE(13)] = 198,
  [SMALL_STATE(14)] = 231,
  [SMALL_STATE(15)] = 264,
  [SMALL_STATE(16)] = 297,
  [SMALL_STATE(17)] = 330,
  [SMALL_STATE(18)] = 363,
  [SMALL_STATE(19)] = 396,
  [SMALL_STATE(20)] = 446,
  [SMALL_STATE(21)] = 504,
  [SMALL_STATE(22)] = 562,
  [SMALL_STATE(23)] = 605,
  [SMALL_STATE(24)] = 645,
  [SMALL_STATE(25)] = 683,
  [SMALL_STATE(26)] = 723,
  [SMALL_STATE(27)] = 761,
  [SMALL_STATE(28)] = 798,
  [SMALL_STATE(29)] = 832,
  [SMALL_STATE(30)] = 857,
  [SMALL_STATE(31)] = 882,
  [SMALL_STATE(32)] = 919,
  [SMALL_STATE(33)] = 956,
  [SMALL_STATE(34)] = 993,
  [SMALL_STATE(35)] = 1030,
  [SMALL_STATE(36)] = 1067,
  [SMALL_STATE(37)] = 1104,
  [SMALL_STATE(38)] = 1141,
  [SMALL_STATE(39)] = 1178,
  [SMALL_STATE(40)] = 1215,
  [SMALL_STATE(41)] = 1252,
  [SMALL_STATE(42)] = 1289,
  [SMALL_STATE(43)] = 1326,
  [SMALL_STATE(44)] = 1347,
  [SMALL_STATE(45)] = 1364,
  [SMALL_STATE(46)] = 1381,
  [SMALL_STATE(47)] = 1397,
  [SMALL_STATE(48)] = 1415,
  [SMALL_STATE(49)] = 1431,
  [SMALL_STATE(50)] = 1446,
  [SMALL_STATE(51)] = 1461,
  [SMALL_STATE(52)] = 1476,
  [SMALL_STATE(53)] = 1491,
  [SMALL_STATE(54)] = 1506,
  [SMALL_STATE(55)] = 1521,
  [SMALL_STATE(56)] = 1540,
  [SMALL_STATE(57)] = 1559,
  [SMALL_STATE(58)] = 1578,
  [SMALL_STATE(59)] = 1597,
  [SMALL_STATE(60)] = 1616,
  [SMALL_STATE(61)] = 1635,
  [SMALL_STATE(62)] = 1654,
  [SMALL_STATE(63)] = 1673,
  [SMALL_STATE(64)] = 1692,
  [SMALL_STATE(65)] = 1711,
  [SMALL_STATE(66)] = 1730,
  [SMALL_STATE(67)] = 1743,
  [SMALL_STATE(68)] = 1754,
  [SMALL_STATE(69)] = 1765,
  [SMALL_STATE(70)] = 1773,
  [SMALL_STATE(71)] = 1783,
  [SMALL_STATE(72)] = 1791,
  [SMALL_STATE(73)] = 1804,
  [SMALL_STATE(74)] = 1811,
  [SMALL_STATE(75)] = 1818,
  [SMALL_STATE(76)] = 1825,
  [SMALL_STATE(77)] = 1835,
  [SMALL_STATE(78)] = 1845,
  [SMALL_STATE(79)] = 1855,
  [SMALL_STATE(80)] = 1865,
  [SMALL_STATE(81)] = 1875,
  [SMALL_STATE(82)] = 1883,
  [SMALL_STATE(83)] = 1893,
  [SMALL_STATE(84)] = 1900,
  [SMALL_STATE(85)] = 1907,
  [SMALL_STATE(86)] = 1914,
  [SMALL_STATE(87)] = 1921,
  [SMALL_STATE(88)] = 1928,
  [SMALL_STATE(89)] = 1935,
  [SMALL_STATE(90)] = 1942,
  [SMALL_STATE(91)] = 1949,
  [SMALL_STATE(92)] = 1954,
  [SMALL_STATE(93)] = 1961,
  [SMALL_STATE(94)] = 1965,
  [SMALL_STATE(95)] = 1969,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__member_access, 2, .production_id = 3),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__member_access, 2, .production_id = 3),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__logical_expression, 3, .production_id = 7),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__logical_expression, 3, .production_id = 7),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arithmetic_expression, 3, .production_id = 7),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__arithmetic_expression, 3, .production_id = 7),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__comparison_expression, 3, .production_id = 6),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__comparison_expression, 3, .production_id = 6),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, .production_id = 1),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, .production_id = 1),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__grouped_expression, 3, .production_id = 3),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__grouped_expression, 3, .production_id = 3),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, .production_id = 8),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 4, .production_id = 8),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 2),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 4),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2, .production_id = 2),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 2, .production_id = 2),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, .production_id = 3),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, .production_id = 3),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 3),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__top_level_item, 1, .production_id = 1),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__top_level_item, 1, .production_id = 1),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 4),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 4), SHIFT_REPEAT(54),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 4), SHIFT_REPEAT(19),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 4), SHIFT_REPEAT(6),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 4), SHIFT_REPEAT(34),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 4), SHIFT_REPEAT(41),
  [108] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 4), SHIFT_REPEAT(36),
  [111] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 4), SHIFT_REPEAT(35),
  [114] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 4), SHIFT_REPEAT(93),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, .production_id = 1),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, .production_id = 3),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_parameter, 3, .production_id = 10),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_definition, 3, .production_id = 5),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_definition, 3, .production_id = 5),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_definition, 6, .production_id = 12),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_definition, 6, .production_id = 12),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_definition, 5, .production_id = 11),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_definition, 5, .production_id = 11),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_definition, 8, .production_id = 13),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_definition, 8, .production_id = 13),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4, .production_id = 9),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 4, .production_id = 9),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, .production_id = 1),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, .production_id = 1),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [217] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(59),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2),
  [222] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(37),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(95),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [248] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [258] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, .production_id = 4), SHIFT_REPEAT(32),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, .production_id = 4),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [265] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(85),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [282] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_nextflow(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
